### ISSUE TITLE
Как это использовать в связке с  Aimylogic ?

### ISSUE THREAD

**Issue by andykov** [mokaton/wild-alice#1]
Спасибо за инструкцию!

Подскажите по дальнейшим шагам пожалуйста.
Я пытаюсь авторизоваться на школьном портале [https://api.school.mosreg.ru/](https://api.school.mosreg.ru/)
[https://login.school.mosreg.ru/oauth2?response_type=<token|code>&client_id=<client_id>&scope=<scope>&redirect_uri=<redirect_uri>&state=<state>](https://login.school.mosreg.ru/oauth2?response_type=<token|code>&client_id=<client_id>&scope=<scope>&redirect_uri=<redirect_uri>&state=<state>)

- Как теперь через конструктор навыков https://aimylogic.com/ отправить пользователю сообщение с кнопкой "Авторизоваться" ?
- Куда прописывать выше упомянутый URL чтобы Алиса авторизовалась на Школьном портале
Или это не реально?

**Comment by mokaton** [comment]
Андрей,
к сожалению не могу подсказать по заданному вами вопросу, так как не имел опыта работы со школьным порталом.
Можете попробовать задать вопрос на [qna.habr.com](https://qna.habr.com), возможно там найдётся кто-то вовлеченный в тему.
